# Generated by Django 2.2.19 on 2022-12-04 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_auto_20221204_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Картинка'),
        ),
    ]
