# Generated by Django 2.2.19 on 2022-11-28 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_auto_20221120_1035'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Favorite',
        ),
    ]
