# Generated by Django 2.2.19 on 2022-12-14 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_auto_20221214_0802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredients',
            name='measurement_unit',
            field=models.CharField(max_length=30, verbose_name='Единица измерения'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=models.CharField(blank=True, default='#000000', max_length=7, null=True, verbose_name='Цветовой HEX-код'),
        ),
    ]
