# Generated by Django 4.1.4 on 2022-12-15 16:06

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_auto_20221214_2001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=colorfield.fields.ColorField(blank=True, default='#FF0000', image_field=None, max_length=7, null=True, samples=None, verbose_name='Цветовой HEX-код'),
        ),
    ]
